// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiaDPWJL91m63myUD1609zv_Bw4bdJEAQ',
    appId: '1:559329487158:web:6ba82abe0f0c12d4156b97',
    messagingSenderId: '559329487158',
    projectId: 'elitenew-f0b99',
    authDomain: 'elitenew-f0b99.firebaseapp.com',
    storageBucket: 'elitenew-f0b99.appspot.com',
    measurementId: 'G-WNV1731NJB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3h_WYiMq-pbTt1JI5hB274r2NxdW2crI',
    appId: '1:559329487158:ios:d64b2c1e54435ead156b97',
    messagingSenderId: '559329487158',
    projectId: 'elitenew-f0b99',
    storageBucket: 'elitenew-f0b99.appspot.com',
    androidClientId: '559329487158-lce7bkk5n7mmjjt4qab0j137o2a2p8e5.apps.googleusercontent.com',
    iosClientId: '559329487158-k8p1dd0lpe781kl9mjfr7qk31r635p9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.elite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3h_WYiMq-pbTt1JI5hB274r2NxdW2crI',
    appId: '1:559329487158:ios:d64b2c1e54435ead156b97',
    messagingSenderId: '559329487158',
    projectId: 'elitenew-f0b99',
    storageBucket: 'elitenew-f0b99.appspot.com',
    androidClientId: '559329487158-lce7bkk5n7mmjjt4qab0j137o2a2p8e5.apps.googleusercontent.com',
    iosClientId: '559329487158-k8p1dd0lpe781kl9mjfr7qk31r635p9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.elite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiaDPWJL91m63myUD1609zv_Bw4bdJEAQ',
    appId: '1:559329487158:web:3fd32a5a59674662156b97',
    messagingSenderId: '559329487158',
    projectId: 'elitenew-f0b99',
    authDomain: 'elitenew-f0b99.firebaseapp.com',
    storageBucket: 'elitenew-f0b99.appspot.com',
    measurementId: 'G-0QF13Y2QZP',
  );

}